import { chromium } from "playwright-core";
const base = "http://localhost:3123";
const browser = await chromium.launch({ channel: "msedge", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(`${base}/work/zibrah-code`, { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
console.log("scrollY:", await page.evaluate(() => window.scrollY));
const cover = await page.$('button[aria-label^="Enlarge cover"]');
if (!cover) throw new Error("no cover button");
const box = await cover.boundingBox();
console.log("cover box:", box);
const nat = await page.evaluate(() => { const img = document.querySelector('button[aria-label^="Enlarge cover"] img'); return { natural: [img.naturalWidth, img.naturalHeight], rendered: [img.clientWidth, img.clientHeight] }; });
console.log("cover img:", nat);
await page.evaluate((y) => window.scrollTo(0, y - 120), box.y);
await page.waitForTimeout(1200);
await page.screenshot({ path: "cover.png" });
await cover.click();
await page.waitForTimeout(1200);
console.log("counter:", await page.evaluate(() => document.querySelector('[role="dialog"] span')?.textContent));
await page.screenshot({ path: "cover-lb.png" });
await page.keyboard.press("ArrowRight");
await page.waitForTimeout(500);
console.log("after right:", await page.evaluate(() => document.querySelector('[role="dialog"] span')?.textContent));
await page.keyboard.press("Escape");
await page.waitForTimeout(400);
console.log("dialog closed:", await page.evaluate(() => !document.querySelector('[role="dialog"]')));
await browser.close();
